# Generated by Django 3.2 on 2024-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='0GxW3MGvj4', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='AL7qzPgYdU', max_length=10),
        ),
    ]
