# Generated by Django 3.2 on 2024-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='TPN1G4CmAz', max_length=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='pFzxSTD58d', max_length=10),
        ),
    ]
