# Generated by Django 3.2 on 2024-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240510_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='lgaJTsJ4ix', max_length=10),
        ),
        migrations.AlterField(
            model_name='recenttransaction',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/transactions'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='NjE4fsjUUl', max_length=10),
        ),
    ]
