# Generated by Django 3.2 on 2024-02-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20240214_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='S0GPkpLb2N', max_length=10),
        ),
        migrations.AlterField(
            model_name='recenttransaction',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='mNjKUdjz29', max_length=10),
        ),
    ]
