# Generated by Django 3.2 on 2024-02-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20240214_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ticker')),
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='ZhLYYaUv5h', max_length=10),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='trnx_hash',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='VmPk0jPPhj', max_length=10),
        ),
    ]
