# Generated by Django 3.2 on 2024-05-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20240516_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='ewBvElFSF8', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='S7rVMCW8lZ', max_length=10),
        ),
    ]
