# Generated by Django 3.2 on 2024-02-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20240216_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(default='1O8sE47Nhg', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='reference',
            field=models.CharField(default='3eX0pgAt8s', max_length=10),
        ),
    ]
