# Generated by Django 3.2 on 2024-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='prev_close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000),
        ),
    ]
